version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      # Trying to emulate the apt-get/systemd clashing problem
      # https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
      - run:
          name: Go to sleep
          command: sleep 60
      - run:
          name: Install PHP
          command: |
            sudo apt-add-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install php7.1
      - run:
          name: Check installed PHP version
          command: |
            php -v
