version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01
    steps:
      - run:
          name: Install PHP
          command: |
            sudo apt-add-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install php7.1
